version: '3.8'

services:
  nestjs-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ai-interview-backend-dev
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    env_file:
      - .env
    # environment:
    #   - MONGODB_URI=mongo_uri 
    

  redis:
    image: redis:7
    container_name: ai-interview-redis
    ports:
      - "6379:6379"

volumes:
  node_modules:
