FROM node:18

# Create app directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

# Use NestJS CLI with --watch for live reload
CMD ["npm", "run", "start:dev"]
