# version: '3.8'

services:
  nestjs-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ai-interview-backend-dev
    ports:
      - "3001:3000"
    volumes:
      - .:/app:cached
    command: npm run start:dev
    env_file:
      - .env
    # environment:
    #   - MONGODB_URI=mongo_uri 
    

  redis:
    image: redis:7
    container_name: ai-interview-redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: ai-interview-rabbitmq
    ports:
      - "5672:5672"   # Main RabbitMQ port
      - "15672:15672" # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  node_modules:
  rabbitmq_data:
